### ISSUE TITLE
Stirling connectivity

### ISSUE THREAD

**Issue by andrewgarner** [guidance-guarantee-programme/switchboard#20]
> On Tuesday this number diverted to CAD and having dialled it on three occasions over the last few days it gives differing results –  ringing out to a message “saying refer to adviceguide.org.uk website for number you want”; ringing out full stop, and Tuesday diverting to a CAD adviser (but queued due to demand). Tried twice on Wednesday and both times got a recorded message that started half way through it saying ‘…….we are closed but will reopen on Monday’.

**Comment by stevenwilkin** [comment]
Close this one as well?
